{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ansible-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansible-ui.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ansible-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansible-ui.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ansible-ui.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ansible-ui.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
